# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d7af07f183a4ccf32adffe5c0ea56ec384f766175a42bcb92fcfe3494f39edc34b143385ad2874a13461b54d64f5fb58e964a7606ec7924cb6850438c820593

test:
  secret_key_base: 09cee037d6c5af60911bb8ecf1fc4d6ed4051a9c80dc5ce477dd069573dd19fce6594b64dcc2e4eb7cd8917e91efc123a4aecc06de58f149e295c5d0f79d610b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
